export const USERS_FETCHING_START = 'USERS_FETCHING_START';
export const USERS_RECEIVE_USERS = 'USERS_RECEIVE_USERS';
export const USERS_CLEAR_LIST = 'USERS_CLEAR_LIST'

export const USER_DETAILS_FETCHING_START = 'USER_DETAILS_FETCHING_START';
export const USER_DETAILS_RECEIVED_DETAILS = 'USER_DETAILS_RECEIVED_DETAILS';
export const USER_DETAILS_RECEIVED_REPOS = 'USER_DETAILS_RECEIVED_REPOS';
